<a href="https://colab.research.google.com/github/jigaurab/DEMO/blob/main/demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import section**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import cv2

Loading dataset

In [ ]:
df=pd.read_csv('fer2013.csv')
df

      emotion                                             pixels     Usage
0           0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...  Training
1           0  151 150 147 155 148 133 111 140 170 174 182 15...  Training
2           2  231 212 156 164 174 138 161 173 182 200 106 38...  Training
3           4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...  Training
4           6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...  Training
...       ...                                                ...       ...
4492        3  245 189 102 200 236 219 212 211 218 243 220 19...  Training
4493        0  6 6 6 6 6 11 64 88 71 118 98 95 142 152 156 16...  Training
4494        3  181 151 51 11 3 2 1 4 2 10 10 11 10 6 9 9 10 1...  Training
4495        5  236 234 235 233 212 192 174 139 110 104 127 13...  Training
4496        0  126 125 126 125 128 116 33 10 14 12 11 8 12 11...       NaN

[4497 rows x 3 columns]

## data splitting

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df['pixels'],df['emotion'],test_size=0.2,shuffle=True)

## testing

In [ ]:
x_train

1877    101 99 99 81 37 31 23 18 24 32 34 49 48 43 48 ...
4376    41 33 18 25 38 43 30 48 55 62 43 56 43 73 95 4...
2357    255 255 255 255 255 255 255 255 255 253 249 24...
1427    135 133 153 64 2 16 16 12 14 35 48 58 78 93 10...
466     33 44 39 39 54 52 50 58 57 66 82 82 68 70 72 6...
                              ...
3418    136 137 132 128 120 106 105 123 130 142 150 14...
3322    31 36 29 19 21 32 52 62 31 16 6 2 4 5 7 7 6 14...
1179    150 150 155 160 164 144 145 189 202 209 207 19...
4173    196 235 172 176 143 159 154 150 134 146 133 18...
2410    168 169 169 168 166 161 157 161 163 160 68 11 ...
Name: pixels, Length: 3597, dtype: object

In [8]:
!ls

fer2013.csv  sample_data